package com.fred.enums;

public enum InterpolationTechnique {
	JACOBSEN_3, JACOBSEN_3_HANNNING, JACOBSEN_3_HAMMING, JACOBSEN_4_HANNING, JACOBSEN_5_HANNING, JACOBSEN_WITH_BIAS_CORRECTION, QUINN1, QUINN2, JACOBSEN_5_HAMMING;
}
